name: Commit checks
on: 
  push:
    branches: '*'
  pull_request:
    types: [opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: ottofeller/github-actions/npm-run@main
      with:
        node-version: 16
        command: npm run typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: ottofeller/github-actions/npm-run@main
      with:
        node-version: 16
        command: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ottofeller/github-actions/npm-run@main
      with:
        node-version: 16
        command: npm run test
